/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Eoghan
 */
public class TypingTutorGUI extends javax.swing.JFrame implements KeyListener {

    Color highlight = new Color(127, 255, 0);
    Color release = new Color(240, 240, 240);

    ArrayList<String> easyLevelPangram = new ArrayList<>();

    String easyPangramOne = "The quick brown fox jumps over the lazy dog";//31+8 spaces =39;
    String easyPangramTwo = "The five boxing wizards jump quickly";//31+5 spaces=36;
    String easyPangramThree = "Waxy and quivering, jocks fumble the pizza";//36+6 spaces =42;

    ArrayList<String> mediumLevelPangram = new ArrayList<>();

    String mediumPangramOne = "Sphinx of black quartz, judge my vow";
    String mediumPangramTwo = "Jackdaws love my big sphinx of quartz";
    String mediumPangramThree = "Two driven jocks help fax my big quiz";

    ArrayList<String> hardLevelPangram = new ArrayList<>();

    String hardPangramOne = "A wizard's job is to vex chumps quickly in fog";
    String hardPangramTwo = "By Jove, my quick study of lexicography won a prize";
    String hardPangramThree = "How vexingly quick daft zebras jump";

    ArrayList<String> tips = new ArrayList<>();

    String tipOne = "Try out all the difficulties to challenge yourself!!!";
    String tipTwo = "Place your fingers on the f and j keys for better accuracy";
    String tipThree = "Check out the leaderboards for your score";

    /**
     * Creates new form TypingTutorGUI
     */
    public TypingTutorGUI() {
        initComponents();
        disableButton();
        displayTextArea.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyButtonGroup = new javax.swing.ButtonGroup();
        displayPanel = new javax.swing.JPanel();
        typingPanel = new javax.swing.JPanel();
        threeButton = new javax.swing.JButton();
        backTickButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        tabButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        openSquareBracketButton = new javax.swing.JButton();
        closeSquareBracketButton = new javax.swing.JButton();
        forwardSlashButton = new javax.swing.JButton();
        capsButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        semicolonButton = new javax.swing.JButton();
        apostropheButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        shiftButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        questionButton = new javax.swing.JButton();
        upArrowButton = new javax.swing.JButton();
        downArrowButton = new javax.swing.JButton();
        spaceButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        messagePanel = new javax.swing.JPanel();
        pangramLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        difficultyPanel = new javax.swing.JPanel();
        hardRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        easyRadioButton = new javax.swing.JRadioButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Typing Application");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        threeButton.setText("3");

        backTickButton.setText("`");

        oneButton.setText("1");

        twoButton.setText("2");

        fourButton.setText("4");

        fiveButton.setText("5");

        sevenButton.setText("7");

        sixButton.setText("6");

        nineButton.setText("9");

        eightButton.setText("8");

        zeroButton.setText("0");

        plusButton.setText("+");

        minusButton.setText("-");

        backspaceButton.setText("backspace");

        tabButton.setText("tab");

        qButton.setText("Q");

        wButton.setText("W");

        eButton.setText("E");

        rButton.setText("R");

        tButton.setText("T");

        yButton.setText("Y");

        uButton.setText("U");

        iButton.setText("I");

        oButton.setText("O");

        pButton.setText("P");

        openSquareBracketButton.setText("[");

        closeSquareBracketButton.setText("]");

        forwardSlashButton.setText("\\");

            capsButton.setText("caps");

            aButton.setText("A");

            sButton.setText("S");

            dButton.setText("D");

            fButton.setText("F");

            gButton.setText("G");

            hButton.setText("H");

            jButton.setText("J");

            kButton.setText("K");

            lButton.setText("L");

            semicolonButton.setText(";");

            apostropheButton.setText("'");

            enterButton.setText("Enter");

            shiftButton.setText("Shift");

            zButton.setText("Z");

            xButton.setText("X");

            cButton.setText("C");

            vButton.setText("V");

            bButton.setText("B");

            nButton.setText("N");

            mButton.setText("M");

            commaButton.setText(",");

            dotButton.setText(".");

            questionButton.setText("?");

            upArrowButton.setText("^");

            downArrowButton.setText("v");

            leftButton.setText("<");

            rightButton.setText(">");

            finishButton.setBackground(new java.awt.Color(102, 153, 255));
            finishButton.setText("Finish");
            finishButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    finishButtonActionPerformed(evt);
                }
            });

            resetButton.setBackground(new java.awt.Color(255, 153, 153));
            resetButton.setText("Reset");
            resetButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    resetButtonActionPerformed(evt);
                }
            });

            exitButton.setBackground(new java.awt.Color(0, 204, 204));
            exitButton.setText("Exit");
            exitButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout typingPanelLayout = new javax.swing.GroupLayout(typingPanel);
            typingPanel.setLayout(typingPanelLayout);
            typingPanelLayout.setHorizontalGroup(
                typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(typingPanelLayout.createSequentialGroup()
                    .addComponent(backTickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(typingPanelLayout.createSequentialGroup()
                    .addComponent(capsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(semicolonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(apostropheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(typingPanelLayout.createSequentialGroup()
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(typingPanelLayout.createSequentialGroup()
                            .addComponent(tabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(qButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(openSquareBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(closeSquareBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(forwardSlashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(typingPanelLayout.createSequentialGroup()
                            .addComponent(shiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(typingPanelLayout.createSequentialGroup()
                                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(125, 125, 125)
                                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(typingPanelLayout.createSequentialGroup()
                                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(spaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(typingPanelLayout.createSequentialGroup()
                                    .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(questionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingPanelLayout.createSequentialGroup()
                                    .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(downArrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(upArrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            typingPanelLayout.setVerticalGroup(
                typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(typingPanelLayout.createSequentialGroup()
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backTickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openSquareBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeSquareBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forwardSlashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semicolonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apostropheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(questionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(upArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );

            typingPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backTickButton, tabButton});

            displayTextArea.setEditable(false);
            displayTextArea.setColumns(20);
            displayTextArea.setRows(5);
            jScrollPane1.setViewportView(displayTextArea);

            pangramLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            pangramLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

            messageLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            messageLabel.setText("Your Message is:");

            javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
            messagePanel.setLayout(messagePanelLayout);
            messagePanelLayout.setHorizontalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pangramLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            messagePanelLayout.setVerticalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pangramLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(51, 102, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("NB: When you have finished click the finish button to find out your score!!!");

            difficultyButtonGroup.add(hardRadioButton);
            hardRadioButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            hardRadioButton.setForeground(new java.awt.Color(220, 20, 60));
            hardRadioButton.setText("Hard");
            hardRadioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    hardRadioButtonActionPerformed(evt);
                }
            });

            difficultyButtonGroup.add(mediumRadioButton);
            mediumRadioButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            mediumRadioButton.setForeground(new java.awt.Color(255, 165, 0));
            mediumRadioButton.setText("Medium");
            mediumRadioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mediumRadioButtonActionPerformed(evt);
                }
            });

            difficultyButtonGroup.add(easyRadioButton);
            easyRadioButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            easyRadioButton.setForeground(new java.awt.Color(0, 153, 0));
            easyRadioButton.setText("Easy");
            easyRadioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    easyRadioButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout difficultyPanelLayout = new javax.swing.GroupLayout(difficultyPanel);
            difficultyPanel.setLayout(difficultyPanelLayout);
            difficultyPanelLayout.setHorizontalGroup(
                difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, difficultyPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(easyRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(140, 140, 140)
                    .addComponent(mediumRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            difficultyPanelLayout.setVerticalGroup(
                difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, difficultyPanelLayout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hardRadioButton)
                        .addComponent(easyRadioButton)
                        .addComponent(mediumRadioButton))
                    .addContainerGap())
            );

            homeButton.setText("Home");
            homeButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    homeButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                                .addComponent(difficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                    .addComponent(difficultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(typingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
//        try {
//            int userInput = displayTextArea.getText().length();
//            int message = pangramLabel.getText().length();
//
//            double result = userInput / message;
//
//            double finalResult = result * 100;
//
//            if (finalResult == 100) {
//                JOptionPane.showMessageDialog(null, " Congratulations you typed it perfectly " + finalResult);
//            } else if (finalResult < 100 && finalResult > 90) {
//                JOptionPane.showMessageDialog(null, "Excellent Work but try again for a perfect score " + finalResult);
//            } else if (finalResult > 60 && finalResult < 90) {
//                JOptionPane.showMessageDialog(null, "Good work but we know you can do better!!! " + finalResult);
//            } else if (finalResult > 40 && finalResult < 60) {
//                JOptionPane.showMessageDialog(null, "Good Effort but try again " + finalResult);
//            } else if (finalResult < 40) {
//                JOptionPane.showMessageDialog(null, "You have failed try again!!! " + finalResult);
//            } else if (finalResult > 100) {
//                JOptionPane.showMessageDialog(null, "Too Many charachters entered try again!!!");
//            }
//        } catch (ArithmeticException e) {
//            JOptionPane.showMessageDialog(null, "No charchters entered", "Error", JOptionPane.ERROR_MESSAGE);
//        }
        int message = pangramLabel.getText().trim().length();
        int userInput = displayTextArea.getText().length();

        int total = message + userInput;
        JOptionPane.showMessageDialog(null, total);
        
        if(total > 40){
            JOptionPane.showMessageDialog(null, "Nice");
        }else{
            JOptionPane.showMessageDialog(null, "Unlucky");
        }
        resetAfterFinish();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        displayTextArea.setText("");
        pangramLabel.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void easyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyRadioButtonActionPerformed
        displayEasyPan(easyLevelPangram);
        fillEasyPan(easyLevelPangram);

        if (easyRadioButton.isSelected()) {

            Random rands = new Random();

            for (int i = 0; i < easyLevelPangram.size(); i++) {
                pangramLabel.setText(easyLevelPangram.get(rands.nextInt(easyLevelPangram.size())));
                pangramLabel.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_easyRadioButtonActionPerformed

    private void mediumRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumRadioButtonActionPerformed
        displayMediumPan(mediumLevelPangram);
        fillMediumPan(mediumLevelPangram);

        if (mediumRadioButton.isSelected()) {
            Random rands = new Random();

            for (int i = 0; i < mediumLevelPangram.size(); i++) {
                pangramLabel.setText(mediumLevelPangram.get(rands.nextInt(mediumLevelPangram.size())));
                pangramLabel.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_mediumRadioButtonActionPerformed

    private void hardRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardRadioButtonActionPerformed
        displayHardPan(hardLevelPangram);
        fillHardPan(hardLevelPangram);

        if (hardRadioButton.isSelected()) {
            Random rands = new Random();

            for (int i = 0; i < hardLevelPangram.size(); i++) {
                pangramLabel.setText(hardLevelPangram.get(rands.nextInt(hardLevelPangram.size())));
                pangramLabel.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_hardRadioButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypingTutorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JButton apostropheButton;
    private javax.swing.JButton bButton;
    private javax.swing.JButton backTickButton;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton capsButton;
    private javax.swing.JButton closeSquareBracketButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton dButton;
    private javax.swing.ButtonGroup difficultyButtonGroup;
    private javax.swing.JPanel difficultyPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton downArrowButton;
    private javax.swing.JButton eButton;
    private javax.swing.JRadioButton easyRadioButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton forwardSlashButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton gButton;
    private javax.swing.JButton hButton;
    private javax.swing.JRadioButton hardRadioButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton iButton;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton mButton;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton nButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton openSquareBracketButton;
    private javax.swing.JButton pButton;
    private javax.swing.JLabel pangramLabel;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton questionButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton sButton;
    private javax.swing.JButton semicolonButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton shiftButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton spaceButton;
    private javax.swing.JButton tButton;
    private javax.swing.JButton tabButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JPanel typingPanel;
    private javax.swing.JButton uButton;
    private javax.swing.JButton upArrowButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

    private void displayEasyPan(ArrayList<String> easyLevelPangram) {
        Random rand = new Random();
        for (int i = 0; i < easyLevelPangram.size(); i++) {
            pangramLabel.setText(easyLevelPangram.get(rand.nextInt(easyLevelPangram.size())));
            pangramLabel.setForeground(Color.RED);
        }
    }

    private void fillEasyPan(ArrayList<String> easyLevelPangram) {
        easyLevelPangram.add(easyPangramOne);
        easyLevelPangram.add(easyPangramTwo);
        easyLevelPangram.add(easyPangramThree);
    }

    public void displayMediumPan(ArrayList<String> mediumLevelPangram) {
        Random rands = new Random();
        for (int i = 0; i < mediumLevelPangram.size(); i++) {
            pangramLabel.setText(mediumLevelPangram.get(rands.nextInt(mediumLevelPangram.size())));
            pangramLabel.setForeground(Color.RED);
        }
    }

    public void fillMediumPan(ArrayList<String> mediumLevelPangram) {
        mediumLevelPangram.add(mediumPangramOne);
        mediumLevelPangram.add(mediumPangramTwo);
        mediumLevelPangram.add(mediumPangramThree);
    }

    public void displayHardPan(ArrayList<String> hardLevelPangram) {
        Random rands = new Random();
        for (int i = 0; i < hardLevelPangram.size(); i++) {
            pangramLabel.setText(hardLevelPangram.get(rands.nextInt(hardLevelPangram.size())));
            pangramLabel.setForeground(Color.RED);
        }
    }

    public void fillHardPan(ArrayList<String> hardLevelPangram) {
        hardLevelPangram.add(hardPangramOne);
        hardLevelPangram.add(hardPangramTwo);
        hardLevelPangram.add(hardPangramThree);
    }

    public void displayTips(ArrayList<String> tips) {

    }

    public void fillTips(ArrayList<String> tips) {

    }

    public void disableButton() {
        backspaceButton.setEnabled(false);
        backTickButton.setEnabled(false);
    }

    public void resetAfterFinish() {
        displayTextArea.setText("");
        pangramLabel.setText("");
    }

    @Override
    public void keyTyped(KeyEvent e) {
        displayTextArea.setText(displayTextArea.getText() + e.getKeyChar());
    }

    @Override
    public void keyPressed(KeyEvent e) {
        //Get The KeyCode
        int keyCode = e.getKeyCode();
        //Switch statement for handling keys pressed
        switch (keyCode) {
            //numbers
            case KeyEvent.VK_0:
                zeroButton.setBackground(highlight);
                break;
            case KeyEvent.VK_1:
                oneButton.setBackground(highlight);
                break;
            case KeyEvent.VK_2:
                twoButton.setBackground(highlight);
                break;
            case KeyEvent.VK_3:
                threeButton.setBackground(highlight);
                break;
            case KeyEvent.VK_4:
                fourButton.setBackground(highlight);
                break;
            case KeyEvent.VK_5:
                fiveButton.setBackground(highlight);
                break;
            case KeyEvent.VK_6:
                sixButton.setBackground(highlight);
                break;
            case KeyEvent.VK_7:
                sevenButton.setBackground(highlight);
                break;
            case KeyEvent.VK_8:
                eightButton.setBackground(highlight);
                break;
            case KeyEvent.VK_9:
                nineButton.setBackground(highlight);
                break;
            //letters
            case KeyEvent.VK_A:
                aButton.setBackground(highlight);
                break;
            case KeyEvent.VK_B:
                bButton.setBackground(highlight);
                break;
            case KeyEvent.VK_C:
                cButton.setBackground(highlight);
                break;
            case KeyEvent.VK_D:
                dButton.setBackground(highlight);
                break;
            case KeyEvent.VK_E:
                eButton.setBackground(highlight);
                break;
            case KeyEvent.VK_F:
                fButton.setBackground(highlight);
                break;
            case KeyEvent.VK_G:
                gButton.setBackground(highlight);
                break;
            case KeyEvent.VK_H:
                hButton.setBackground(highlight);
                break;
            case KeyEvent.VK_I:
                iButton.setBackground(highlight);
                break;
            case KeyEvent.VK_J:
                jButton.setBackground(highlight);
                break;
            case KeyEvent.VK_K:
                kButton.setBackground(highlight);
                break;
            case KeyEvent.VK_L:
                lButton.setBackground(highlight);
                break;
            case KeyEvent.VK_M:
                mButton.setBackground(highlight);
                break;
            case KeyEvent.VK_N:
                nButton.setBackground(highlight);
                break;
            case KeyEvent.VK_O:
                oButton.setBackground(highlight);
                break;
            case KeyEvent.VK_P:
                pButton.setBackground(highlight);
                break;
            case KeyEvent.VK_Q:
                qButton.setBackground(highlight);
                break;
            case KeyEvent.VK_R:
                rButton.setBackground(highlight);
                break;
            case KeyEvent.VK_S:
                sButton.setBackground(highlight);
                break;
            case KeyEvent.VK_T:
                tButton.setBackground(highlight);
                break;
            case KeyEvent.VK_U:
                uButton.setBackground(highlight);
                break;
            case KeyEvent.VK_V:
                vButton.setBackground(highlight);
                break;
            case KeyEvent.VK_W:
                wButton.setBackground(highlight);
                break;
            case KeyEvent.VK_X:
                xButton.setBackground(highlight);
                break;
            case KeyEvent.VK_Y:
                yButton.setBackground(highlight);
                break;
            case KeyEvent.VK_Z:
                zButton.setBackground(highlight);
                break;
            //special charachters
            case KeyEvent.VK_OPEN_BRACKET:
                openSquareBracketButton.setBackground(highlight);
                break;
            case KeyEvent.VK_CLOSE_BRACKET:
                closeSquareBracketButton.setBackground(highlight);
                break;
            case KeyEvent.VK_MINUS:
                minusButton.setBackground(highlight);
                break;
//            case KeyEvent.VK_EQUALS+KeyEvent.VK_SHIFT:
//                plusButton.setBackground(highlight);
//                break;
            case KeyEvent.VK_BACK_SPACE:
                backspaceButton.setBackground(highlight);
                break;
            case KeyEvent.VK_TAB:
                tabButton.setBackground(highlight);
                break;
            case KeyEvent.VK_CAPS_LOCK:
                capsButton.setBackground(highlight);
                break;
            case KeyEvent.VK_SHIFT:
                shiftButton.setBackground(highlight);
                break;
            case KeyEvent.VK_BACK_SLASH:
                forwardSlashButton.setBackground(highlight);
                break;
            case KeyEvent.VK_SEMICOLON:
                semicolonButton.setBackground(highlight);
                break;
            case KeyEvent.VK_QUOTE:
                apostropheButton.setBackground(highlight);
                break;
            case KeyEvent.VK_ENTER:
                enterButton.setBackground(highlight);
                break;
            case KeyEvent.VK_COMMA:
                commaButton.setBackground(highlight);
                break;
            case KeyEvent.VK_PERIOD:
                dotButton.setBackground(highlight);
                break;
            case KeyEvent.VK_UP:
                upArrowButton.setBackground(highlight);
                break;
            case KeyEvent.VK_LEFT:
                leftButton.setBackground(highlight);
                break;
            case KeyEvent.VK_RIGHT:
                rightButton.setBackground(highlight);
                break;
            case KeyEvent.VK_DOWN:
                downArrowButton.setBackground(highlight);
                break;
            case KeyEvent.VK_SPACE:
                spaceButton.setBackground(highlight);
                break;

        }

    }

    @Override
    public void keyReleased(KeyEvent e) {
        int keyCode = e.getKeyCode();

        switch (keyCode) {
            //numbers
            case KeyEvent.VK_0:
                zeroButton.setBackground(release);
                break;
            case KeyEvent.VK_1:
                oneButton.setBackground(release);
                break;
            case KeyEvent.VK_2:
                twoButton.setBackground(release);
                break;
            case KeyEvent.VK_3:
                threeButton.setBackground(release);
                break;
            case KeyEvent.VK_4:
                fourButton.setBackground(release);
                break;
            case KeyEvent.VK_5:
                fiveButton.setBackground(release);
                break;
            case KeyEvent.VK_6:
                sixButton.setBackground(release);
                break;
            case KeyEvent.VK_7:
                sevenButton.setBackground(release);
                break;
            case KeyEvent.VK_8:
                eightButton.setBackground(release);
                break;
            case KeyEvent.VK_9:
                nineButton.setBackground(release);
                break;
            //letters
            case KeyEvent.VK_A:
                aButton.setBackground(release);
                break;
            case KeyEvent.VK_B:
                bButton.setBackground(release);
                break;
            case KeyEvent.VK_C:
                cButton.setBackground(release);
                break;
            case KeyEvent.VK_D:
                dButton.setBackground(release);
                break;
            case KeyEvent.VK_E:
                eButton.setBackground(release);
                break;
            case KeyEvent.VK_F:
                fButton.setBackground(release);
                break;
            case KeyEvent.VK_G:
                gButton.setBackground(release);
                break;
            case KeyEvent.VK_H:
                hButton.setBackground(release);
                break;
            case KeyEvent.VK_I:
                iButton.setBackground(release);
                break;
            case KeyEvent.VK_J:
                jButton.setBackground(release);
                break;
            case KeyEvent.VK_K:
                kButton.setBackground(release);
                break;
            case KeyEvent.VK_L:
                lButton.setBackground(release);
                break;
            case KeyEvent.VK_M:
                mButton.setBackground(release);
                break;
            case KeyEvent.VK_N:
                nButton.setBackground(release);
                break;
            case KeyEvent.VK_O:
                oButton.setBackground(release);
                break;
            case KeyEvent.VK_P:
                pButton.setBackground(release);
                break;
            case KeyEvent.VK_Q:
                qButton.setBackground(release);
                break;
            case KeyEvent.VK_R:
                rButton.setBackground(release);
                break;
            case KeyEvent.VK_S:
                sButton.setBackground(release);
                break;
            case KeyEvent.VK_T:
                tButton.setBackground(release);
                break;
            case KeyEvent.VK_U:
                uButton.setBackground(release);
                break;
            case KeyEvent.VK_V:
                vButton.setBackground(release);
                break;
            case KeyEvent.VK_W:
                wButton.setBackground(release);
                break;
            case KeyEvent.VK_X:
                xButton.setBackground(release);
                break;
            case KeyEvent.VK_Y:
                yButton.setBackground(release);
                break;
            case KeyEvent.VK_Z:
                zButton.setBackground(release);
                break;
            //special charachters 
            case KeyEvent.VK_OPEN_BRACKET:
                openSquareBracketButton.setBackground(release);
                break;
            case KeyEvent.VK_CLOSE_BRACKET:
                closeSquareBracketButton.setBackground(release);
                break;
            case KeyEvent.VK_MINUS:
                minusButton.setBackground(release);
                break;
            case KeyEvent.VK_PLUS:
                plusButton.setBackground(release);
                break;
            case KeyEvent.VK_BACK_SPACE:
                backspaceButton.setBackground(release);
                break;
            case KeyEvent.VK_TAB:
                tabButton.setBackground(release);
                break;
            case KeyEvent.VK_CAPS_LOCK:
                capsButton.setBackground(release);
                break;
            case KeyEvent.VK_SHIFT:
                shiftButton.setBackground(release);
                break;
            case KeyEvent.VK_BACK_SLASH:
                forwardSlashButton.setBackground(release);
                break;
            case KeyEvent.VK_SEMICOLON:
                semicolonButton.setBackground(release);
                break;
            case KeyEvent.VK_QUOTE:
                apostropheButton.setBackground(release);
                break;
            case KeyEvent.VK_ENTER:
                enterButton.setBackground(release);
                break;
            case KeyEvent.VK_COMMA:
                commaButton.setBackground(release);
                break;
            case KeyEvent.VK_PERIOD:
                dotButton.setBackground(release);
                break;
            case KeyEvent.VK_UP:
                upArrowButton.setBackground(release);
                break;
            case KeyEvent.VK_LEFT:
                leftButton.setBackground(release);
                break;
            case KeyEvent.VK_RIGHT:
                rightButton.setBackground(release);
                break;
            case KeyEvent.VK_DOWN:
                downArrowButton.setBackground(release);
                break;
            case KeyEvent.VK_SPACE:
                spaceButton.setBackground(release);
                break;
        }
    }

    //TO DO: ADD TIPS FOR EXTRA FEATURE, UPDATE GUI, Add login to constructor.
}
